version: '3'

services:
    web:
        container_name: prestation_web
        tty: true
        build: docker/web
        volumes:
            - .:/var/www/prestation
        ports:
            - 8083:80
