server {
   listen 80;
   server_name localhost;
   root /var/www/prestation/public;
   location / {
       try_files $uri /index.php$is_args$args;
   }
   location ~ ^/(index|github|packagist-stats)\.php(/|$) {
       fastcgi_pass unix:/run/php/php7.2-fpm.sock;
       fastcgi_split_path_info ^(.+\.php)(/.*)$;
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_param HTTPS off;
   }
   error_log /var/log/nginx/prestation_error.log;
   access_log /var/log/nginx/prestation_access.log;
}
